config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get 'logout', to: "session#destroy", as: 'logout'
  post "/", to: "session#create", as: 'login'

  get "/auth/google_oauth2/callback", to: "session#create_from_google"
  get '/patients/activity_filter', to: "activities#index"

  namespace "api" do
    namespace "v1" do
      resources :doctors, only: [:index]
    end
  end

  get "/patients/:patient_id/doctors/add/:doctor_id", to: "patients/doctors#create"

  resources :users, only: [:new, :create, :update]

  resources :doctors, only: [:show] do
    scope module: 'provider' do
      resources :messages, only: [:new, :create]
      resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :patients, only: [:index]
      resources :articles, only: [:index, :create]
    end
    get "/tools", to: "provider/tools#index"
  end

  resources :patients, only: [:new, :create, :show] do
    resources :appointments, only: [:index, :destroy]
    resources :medications do
      resources :note, only: [:update]
    end
    resources :doctors do
      resources :note, only: [:update]
    end
    resources :messages, only: [:new, :create]
    post "/new_doctor", to: "patients/doctors#create"
    post "/doctors/new_doctor", to: "patients/doctors#create"
    resources :activities
    resources :exercises, only: [:index]
    resources :articles, only: [:index, :create]
    resources :find_doctor, only: [:index, :create]
  end

  namespace :admin do
    resources :welcome, only: [:index]
    resources :patients, only: [:index]
    resources :doctors, only: [:index]
    resources :medications, only: [:index]
    resources :exercises
    resources :note, only: [:index]
  end

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :date, :time, presence: true
  belongs_to :patient
  belongs_to :doctor

  scope :future, -> {where("date >= '#{DateTime.now}'")}
  scope :past, -> {where("date < '#{DateTime.now}'")}
  scope :today, -> {where(date: Date.today...Date.today+1)}
  scope :sorted_by_time, -> {order(:time)}
  scope :sorted_by_date, -> {order(:date)}

  # This method is needed for simple_calendar gem
  def start_time
    self.date
  end

  def pretty_time
    time.strftime("%I:%M %p")
  end

  def past_appointment?
    return true if date < Date.today
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = current_user.appointments.sorted_by_time
    @appointment = Appointment.new
  end

  def destroy
    appointment = current_user.appointments.find(params[:id])
    appointment.destroy
    redirect_to patient_appointments_path(current_user)
  end

end

app/controllers/provider/appointments_controller.rb
class Provider::AppointmentsController < ApplicationController

  def index
    @appointments = current_user.appointments
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_user.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(current_user)
    else
      render :new
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = current_user.appointments.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to doctor_appointments_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    appointment = current_user.appointments.find(params[:id])
    appointment.destroy
    redirect_to doctor_appointments_path(current_user)
  end

  private

    def appointment_params
      params.require(:appointment).permit(:date, :time, :patient_id)
    end
end

app/controllers/provider/articles_controller.rb
class Provider::ArticlesController < ApplicationController

    def index
      @articles = []
    end

    def pubmed_ids(search, year)
      response = Faraday.get("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=#{search}+AND+#{year}[pdat]")
      unprocessed_ids = Nokogiri::XML(response.body).xpath("//Id")
      unprocessed_ids.map {|element| element.children.text}
    end

    def get_articles(search, year)
      summaries = Faraday.get("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=#{pubmed_ids(search, year).join(",")}")
      unprocessed_titles = Nokogiri::XML(summaries.body).xpath('//*[@Name="Title"]')
      titles = unprocessed_titles.map {|element| element.children.text}
      pubmed_ids(search, year).zip(titles)
    end

    def create
      @year = params[:year]
      @search = params[:search]
      @articles = get_articles(@search, @year)
      render :index
    end

end

app/controllers/provider/messages_controller.rb
class Provider::MessagesController < ApplicationController

  def new
    @patient = current_user.patients.find(params[:patient].to_i)
    @message = Message.new
    @message_history = Message.conversation(@patient, current_user)
  end

  def create
    @patient = current_user.patients.find(params[:message][:patient].to_i)
    @message = current_user.messages.new(message_params)
    @message.patient = @patient
    if @message.save
      flash[:notice] = "Message was sent successfully!"
      redirect_to doctor_patients_path(current_user)
    else
      flash[:notice] = "Sorry, message did not send properly. Please try again."
      render :new
    end
  end

  private

    def message_params
      params.require(:message).permit(:title, :content)
    end
end

app/controllers/provider/patients_controller.rb
class Provider::PatientsController < ApplicationController

  def index
    @patients = current_user.patients.sorted_by_last_name
  end

end

app/controllers/provider/tools_controller.rb
class Provider::ToolsController < ApplicationController

  def index
  end

end

app/views/provider/appointments/edit.html.erb
<%= render partial: "partials/doctor_header"%>

<div class="column-container">
  <h3>Change an Appointment:</h3>
  <div class="column-form">
    <%= form_for [current_user, @appointment] do |f|%>
      <div><%= f.date_field :date, class: "entry-form" %></div>
      <div><%= f.time_field :time,class: "entry-form" %></div>
      <div><%= f.collection_select :patient_id, current_user.patients, :id, :full_name, {}, class: "entry-form" %></div>
      <div><%= f.submit id: "submit-button"%></div><br>
    <% end %>
    <div><%= button_to "Delete Appointment", doctor_appointment_path(current_user, @appointment), method: :delete, id: "delete-button" %></div>
  </div>
</div>

<%= render partial: "partials/doctor_footer"%>

app/views/provider/appointments/index.html.erb
<%= render partial: "partials/doctor_header" %>

<div class="column-container-left">
  <%= link_to "Schedule New Appointment", new_doctor_appointment_path(current_user), id: "new-appointment" %>
  <%= month_calendar events: @appointments do |date, appointments| %>
    <%= date.day %>
    <% appointments.each do |appointment| %>
      <div class="appointment-on-calendar">
        <div class="appointment-info">
          <h4><%= appointment.patient.full_name %></h4>
        </div>
        <%= link_to appointment.time.strftime("%I:%M %p"), edit_doctor_appointment_path(current_user, appointment) %>
      </div>
      <br>
    <% end %>
  <% end %>
  <br>
</div>

<%= render partial: "partials/doctor_footer" %>

app/views/provider/appointments/new.html.erb
<%= render partial: "partials/doctor_header"%>
<div class="column-container">
  <h3>Make a New Appointment:</h3>
  <div class="column-form">
    <%= form_for [current_user, @appointment] do |f|%>
    <div><%= f.collection_select :patient_id, current_user.patients, :id, :full_name, {}, class: "entry-form" %></div>
    <div><%= f.date_field :date, class: "entry-form" %></div>
    <div><%= f.time_field :time,class: "entry-form" %></div>
    <div><%= f.submit id: "submit-button"%></div>
    <% end %>
  </div>
</div>
<%= render partial: "partials/doctor_footer"%>